// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj6223-A4QkfrzZd75tVAal36Sx9JQm-k',
    appId: '1:119513656180:web:337f0c8da3f2c5d7091a21',
    messagingSenderId: '119513656180',
    projectId: 'nutrikidney-base1',
    authDomain: 'nutrikidney-base1.firebaseapp.com',
    databaseURL:
        'https://nutrikidney-base1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrikidney-base1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTtmrP1oOiC8uG578fSgXthnHAuz5IOg',
    appId: '1:119513656180:android:1f8e80df2883b2c7091a21',
    messagingSenderId: '119513656180',
    projectId: 'nutrikidney-base1',
    databaseURL: 'https://nutrikidney-base1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrikidney-base1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTtmrP1oOiC8uG578fSgXthnHAuz5IOg',
    appId: '1:119513656180:ios:placeholder',
    messagingSenderId: '119513656180',
    projectId: 'nutrikidney-base1',
    databaseURL: 'https://nutrikidney-base1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrikidney-base1.firebasestorage.app',
    iosBundleId: 'com.example.nutriKidney',
  );
}
