// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTtmrP1oOiC8uG578fSgXthnHAuz5IOg',
    appId: '1:119513656180:android:1f8e80df2883b2c7091a21',
    messagingSenderId: '119513656180',
    projectId: 'nutrikidney-base1',
    databaseURL: 'https://nutrikidney-base1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrikidney-base1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTtmrP1oOiC8uG578fSgXthnHAuz5IOg',
    appId: '1:119513656180:ios:placeholder',
    messagingSenderId: '119513656180',
    projectId: 'nutrikidney-base1',
    databaseURL: 'https://nutrikidney-base1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrikidney-base1.firebasestorage.app',
    iosBundleId: 'com.example.nutriKidney',
  );
}
